# Generated by Django 5.0.7 on 2024-11-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencia',
            options={'ordering': ['-fecha'], 'verbose_name': 'Emergencia', 'verbose_name_plural': 'Emergencias'},
        ),
        migrations.AlterField(
            model_name='emergencia',
            name='num_victimas',
            field=models.PositiveIntegerField(),
        ),
    ]
